/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package personalFinance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootConfiguration
@SpringBootApplication(scanBasePackages = "personalFinance")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
