/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package personal.finance;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import personal.finance.model.User;
import personal.finance.utils.HibernateUtil;

import javax.persistence.Query;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();

        Session session = sessionFactory.openSession();
        Transaction tx = session.beginTransaction();

        User user = new User();
        session.save(user);

        String queryString = "FROM User u WHERE u.name =\'name\'";
        Query query = session.createQuery(queryString);
        user = (User) query.getSingleResult();

        session.save(user);

        tx.commit();

        session.close();
    }
}