/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package personal.finance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan("personal.finance")
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}